#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require 'yaml_smith'

  if ARGV.first == 'add' && ARGV.length == 4
    YamlSmith::AddKey.call(ARGV[1], ARGV[2], ARGV[3])
  else
    warn 'Usage: yaml-smith add FILE KEY VALUE'
    exit 1
  end
rescue YamlSmith::Error => e
  warn e.message
  exit 1
end
